# Generated by Django 6.0.2 on 2026-02-11 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'essay categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplementEssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True)),
                ('word_limit', models.IntegerField(blank=True, null=True)),
                ('char_limit', models.IntegerField(blank=True, null=True)),
                ('response', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('', '—'), ('wip', 'WIP'), ('done', 'Done'), ('maybe', 'Maybe')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essays', to='supplements.essaycategory')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to='colleges.college')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
