# Generated by Django 6.0.2 on 2026-03-18 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_applicant_coreactivity_applicant'),
        ('supplements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementessay',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essays', to='core.applicant'),
        ),
    ]
