# Generated by Django 6.0.2 on 2026-03-25 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_restore_profile_picture'),
        ('supplements', '0002_supplementessay_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonAppEssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_choice', models.IntegerField(blank=True, null=True)),
                ('response', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('', '—'), ('wip', 'WIP'), ('done', 'Done'), ('maybe', 'Maybe')], max_length=10)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='common_app_essay', to='core.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='UCPersonalInsightQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('response', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('', '—'), ('wip', 'WIP'), ('done', 'Done'), ('maybe', 'Maybe')], max_length=10)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uc_piqs', to='core.applicant')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('applicant', 'question_number')},
            },
        ),
    ]
