# Generated by Django 6.0.2 on 2026-07-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0004_backfill_essay_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonappessay',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('idea', 'Idea Stage'), ('wip', 'WIP'), ('drafted', 'Drafted'), ('done', 'DONE')], default='todo', max_length=10),
        ),
        migrations.AlterField(
            model_name='supplementessay',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('idea', 'Idea Stage'), ('wip', 'WIP'), ('drafted', 'Drafted'), ('done', 'DONE')], default='todo', max_length=10),
        ),
        migrations.AlterField(
            model_name='ucpersonalinsightquestion',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('idea', 'Idea Stage'), ('wip', 'WIP'), ('drafted', 'Drafted'), ('done', 'DONE')], default='todo', max_length=10),
        ),
    ]
