# Generated by Django 6.0.2 on 2026-07-15 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_applicant_word_counter_draft'),
        ('supplements', '0006_migrate_essay_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaycategory',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essay_tags', to='core.applicant'),
        ),
        migrations.AddConstraint(
            model_name='essaycategory',
            constraint=models.UniqueConstraint(fields=('applicant', 'name'), name='unique_tag_name_per_applicant'),
        ),
    ]
