# Generated by Django 6.0.2 on 2026-07-15 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0008_tags_per_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('word_limit', models.IntegerField(blank=True, null=True)),
                ('char_limit', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='supplements.supplementessay')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='supplementessay',
            name='selected_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='supplements.essayprompt'),
        ),
    ]
