# Generated by Django 6.0.2 on 2026-07-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0010_backfill_essay_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementessay',
            name='char_limit_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplementessay',
            name='word_limit_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
