# Generated by Django 6.0.2 on 2026-03-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_test_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='brainstorm',
            field=models.TextField(blank=True),
        ),
    ]
