# Generated by Django 6.0.2 on 2026-03-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_applicant_brainstorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreactivity',
            name='grade_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreactivity',
            name='grade_11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreactivity',
            name='grade_12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreactivity',
            name='grade_9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreactivity',
            name='hours_per_week',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='coreactivity',
            name='weeks_per_year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
