# Generated by Django 6.0.2 on 2026-03-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_hedgie_wedgie'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='uploaded_picture',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='profile_picture',
            field=models.CharField(blank=True, default='img/default_profile.png', max_length=300),
        ),
    ]
