# Generated by Django 6.0.2 on 2026-03-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_uploaded_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='uploaded_picture',
        ),
    ]
