# Generated by Django 6.0.2 on 2026-03-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_profile_picture_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
