# Generated by Django 6.0.2 on 2026-07-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fix_hedgie_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='focus_draft',
            field=models.TextField(blank=True),
        ),
    ]
