# Generated by Django 6.0.2 on 2026-07-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_applicant_focus_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='word_counter_draft',
            field=models.TextField(blank=True),
        ),
    ]
