# Generated by Django 6.0.2 on 2026-07-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_applicant_word_counter_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='considering_mens_colleges',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='considering_womens_colleges',
            field=models.BooleanField(default=True),
        ),
    ]
