# Generated by Django 6.0.2 on 2026-02-11 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonAppActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('activity_type', models.CharField(choices=[('academic', 'Academic'), ('art', 'Art'), ('athletics_club', 'Athletics: Club'), ('athletics_jv_varsity', 'Athletics: JV/Varsity'), ('career', 'Career Oriented'), ('community', 'Community Service (Volunteer)'), ('computer_technology', 'Computer/Technology'), ('cultural', 'Cultural'), ('dance', 'Dance'), ('debate_speech', 'Debate/Speech'), ('environmental', 'Environmental'), ('family_responsibilities', 'Family Responsibilities'), ('foreign_exchange', 'Foreign Exchange'), ('journalism_publication', 'Journalism/Publication'), ('junior_rotc', 'Junior R.O.T.C.'), ('lgbtq', 'LGBT'), ('music_instrumental', 'Music: Instrumental'), ('music_vocal', 'Music: Vocal'), ('religious', 'Religious'), ('research', 'Research'), ('robotics', 'Robotics'), ('school_spirit', 'School Spirit'), ('science_math', 'Science/Math'), ('student_govt', 'Student Govt./Politics'), ('theater_drama', 'Theater/Drama'), ('work_paid', 'Work (Paid)'), ('other', 'Other Club/Activity')], max_length=30)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('grade_9', models.BooleanField(default=False)),
                ('grade_10', models.BooleanField(default=False)),
                ('grade_11', models.BooleanField(default=False)),
                ('grade_12', models.BooleanField(default=False)),
                ('timing_school', models.BooleanField(default=False)),
                ('timing_breaks', models.BooleanField(default=False)),
                ('timing_all_year', models.BooleanField(default=False)),
                ('hours_per_week', models.IntegerField(blank=True, null=True)),
                ('weeks_per_year', models.IntegerField(blank=True, null=True)),
                ('similar_in_college', models.BooleanField(blank=True, null=True)),
                ('personal_notes', models.TextField(blank=True)),
                ('core_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_app_activities', to='core.coreactivity')),
            ],
            options={
                'verbose_name': 'Common App activity',
                'verbose_name_plural': 'Common App activities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CommonAppHonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('grade_9', models.BooleanField(default=False)),
                ('grade_10', models.BooleanField(default=False)),
                ('grade_11', models.BooleanField(default=False)),
                ('grade_12', models.BooleanField(default=False)),
                ('level_school', models.BooleanField(default=False)),
                ('level_state_regional', models.BooleanField(default=False)),
                ('level_national', models.BooleanField(default=False)),
                ('level_international', models.BooleanField(default=False)),
                ('personal_notes', models.TextField(blank=True)),
                ('core_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_app_honors', to='core.coreactivity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MITEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('job', 'Job'), ('activity', 'Activity'), ('summer', 'Summer activity'), ('scholastic', 'Scholastic distinction'), ('non_scholastic', 'Non-scholastic distinction')], max_length=20)),
                ('org_name', models.CharField(blank=True, max_length=200)),
                ('role_award', models.CharField(blank=True, max_length=200)),
                ('participation_period', models.CharField(blank=True, max_length=100)),
                ('hours_per_week', models.IntegerField(blank=True, null=True)),
                ('weeks_per_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('personal_notes', models.TextField(blank=True)),
                ('core_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mit_entries', to='core.coreactivity')),
            ],
            options={
                'verbose_name': 'MIT entry',
                'verbose_name_plural': 'MIT entries',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UCEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('award', 'Award or honor'), ('edu_prep', 'Educational preparation program'), ('extracurricular', 'Extracurricular activity'), ('volunteer', 'Volunteer / Community Service'), ('work', 'Work experience'), ('coursework', 'Other coursework')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('background', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=350)),
                ('grade_9', models.BooleanField(default=False)),
                ('grade_10', models.BooleanField(default=False)),
                ('grade_11', models.BooleanField(default=False)),
                ('grade_12', models.BooleanField(default=False)),
                ('hours_per_week', models.CharField(blank=True, max_length=20)),
                ('weeks_per_year', models.CharField(blank=True, max_length=20)),
                ('recognition_level', models.CharField(blank=True, max_length=50)),
                ('is_academic', models.BooleanField(blank=True, null=True)),
                ('earnings_usage', models.CharField(blank=True, max_length=250)),
                ('still_working', models.BooleanField(blank=True, null=True)),
                ('personal_notes', models.TextField(blank=True)),
                ('core_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uc_entries', to='core.coreactivity')),
            ],
            options={
                'verbose_name': 'UC activity/award',
                'verbose_name_plural': 'UC activities & awards',
                'ordering': ['order'],
            },
        ),
    ]
