# Generated by Django 6.0.2 on 2026-03-18 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('core', '0002_applicant_coreactivity_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonappactivity',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_app_activities', to='core.applicant'),
        ),
        migrations.AddField(
            model_name='commonapphonor',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_app_honors', to='core.applicant'),
        ),
        migrations.AddField(
            model_name='mitentry',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mit_entries', to='core.applicant'),
        ),
        migrations.AddField(
            model_name='ucentry',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uc_entries', to='core.applicant'),
        ),
    ]
