# Generated by Django 6.0.2 on 2026-03-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_commonappactivity_applicant_commonapphonor_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonappactivity',
            name='position',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
