# Generated by Django 6.0.2 on 2026-02-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('apply_status', models.CharField(blank=True, choices=[('applying', 'Applying'), ('likely', 'Likely'), ('considering', 'Considering'), ('unlikely', 'Unlikely'), ('not_applying', 'Not Applying'), ('applied', 'Applied'), ('accepted', 'Accepted'), ('deferred', 'Deferred'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], max_length=20)),
                ('tier', models.CharField(blank=True, max_length=10)),
                ('acceptance_rate', models.CharField(blank=True, max_length=10)),
                ('collegevine_chance', models.CharField(blank=True, max_length=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('app_platform', models.CharField(blank=True, max_length=50)),
                ('terms', models.CharField(blank=True, max_length=50)),
                ('cost_of_attendance', models.CharField(blank=True, max_length=100)),
                ('estimated_financial_aid', models.CharField(blank=True, max_length=100)),
                ('estimated_net_cost', models.CharField(blank=True, max_length=100)),
                ('financial_aid_deadline', models.CharField(blank=True, max_length=20)),
                ('fafsa_required', models.BooleanField(blank=True, null=True)),
                ('css_profile_required', models.BooleanField(blank=True, null=True)),
                ('requirements_style', models.CharField(blank=True, max_length=50)),
                ('intended_major', models.CharField(blank=True, max_length=100)),
                ('second_choice_major', models.CharField(blank=True, max_length=100)),
                ('third_choice_major', models.CharField(blank=True, max_length=100)),
                ('restrictive_ea', models.CharField(blank=True, max_length=5)),
                ('ea_deadline', models.CharField(blank=True, max_length=20)),
                ('ed1_deadline', models.CharField(blank=True, max_length=20)),
                ('ed2_deadline', models.CharField(blank=True, max_length=20)),
                ('rd_deadline', models.CharField(blank=True, max_length=20)),
                ('other_deadline', models.CharField(blank=True, max_length=20)),
                ('self_report_sat', models.CharField(blank=True, max_length=20)),
                ('interview', models.CharField(blank=True, max_length=50)),
                ('known_students', models.TextField(blank=True)),
                ('known_faculty', models.TextField(blank=True)),
                ('toured', models.CharField(blank=True, max_length=20)),
                ('portal_info', models.TextField(blank=True)),
                ('applicant_notes', models.TextField(blank=True)),
                ('parent_notes', models.TextField(blank=True)),
                ('random_notes', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
