# Generated by Django 6.0.2 on 2026-03-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_college_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='sat_avg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='undergrad_enrollment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
