# Generated by Django 6.0.2 on 2026-03-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_populate_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('safety', 'Safety'), ('target', 'Target'), ('reach', 'Reach')], max_length=10),
        ),
        migrations.AlterField(
            model_name='college',
            name='apply_status',
            field=models.CharField(choices=[('applying', 'Applying'), ('likely', 'Likely'), ('considering', 'Considering'), ('unlikely', 'Unlikely'), ('not_applying', 'Not Applying'), ('applied', 'Submitted'), ('accepted', 'Accepted'), ('deferred', 'Deferred'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled'), ('withdrawn', 'Withdrawn')], default='not_applying', max_length=20),
        ),
    ]
