# Generated by Django 6.0.2 on 2026-03-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_canonical_college'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercollege',
            options={'ordering': ['order', 'college__name']},
        ),
        migrations.AlterField(
            model_name='college',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usercollege',
            name='acceptance_rate_override',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usercollege',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
