# Generated by Django 6.0.2 on 2026-07-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0011_normalize_app_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollege',
            name='application_round',
            field=models.CharField(blank=True, choices=[('ea', 'EA'), ('ed1', 'ED I'), ('ed2', 'ED II'), ('rd', 'RD'), ('rolling', 'Rolling')], max_length=10),
        ),
        migrations.AddField(
            model_name='usercollege',
            name='deadline_ordinal',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usercollege',
            name='deadline_override',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usercollege',
            name='apply_status',
            field=models.CharField(choices=[('not_applying', 'Not Applying'), ('considering', 'Considering'), ('applying', 'Applying'), ('applied', 'Submitted'), ('deferred', 'Deferred'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('likely', 'Likely'), ('unlikely', 'Unlikely'), ('enrolled', 'Enrolled'), ('withdrawn', 'Withdrawn')], default='not_applying', max_length=20),
        ),
    ]
