# Generated by Django 6.0.2 on 2026-07-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0013_deadline_sentinels_and_ordinals'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='gender_admission',
            field=models.CharField(choices=[('all', 'All genders'), ('women', "Women's college"), ('men', "Men's college")], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='college',
            name='proof_acceptances',
            field=models.FloatField(default=0),
        ),
    ]
